version: '3'
services:
  aptly:
    container_name: aptly
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 80
        host_ip: 0.0.0.0
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - aptly-data:/opt/aptly

volumes:
  aptly-data:
    external: true
